import smtplib
import streamlit as st
from email.message import EmailMessage


def send_email_alert(
    email,
    district,
    river,
    risk_level,
    confidence
):
    """
    Send a real flood-risk email notification to the
    email address entered by the dashboard user.
    """

    try:
        # Read credentials securely from .streamlit/secrets.toml
        sender_email = st.secrets["email"]["sender_email"]
        app_password = st.secrets["email"]["app_password"]

        # Create email
        msg = EmailMessage()

        msg["From"] = f"SriFloodXAI <{sender_email}>"
        msg["To"] = email
        msg["Subject"] = f"🚨 SriFloodXAI {risk_level} Flood Risk Alert"

        msg.set_content(
            f"""
SriFloodXAI Flood Risk Notification

Risk Level: {risk_level}
Flood Probability: {confidence:.2f}%

District: {district}
River: {river}

Recommended Action:
Please monitor official Disaster Management Centre (DMC)
and local authority announcements for further instructions.

This notification was generated by the SriFloodXAI
AI-Based Flood Prediction and Early Warning System.

Important:
This AI prediction is decision-support information and
does not replace official government flood warnings.
"""
        )

        # Connect securely to Gmail SMTP
        with smtplib.SMTP("smtp.gmail.com", 587, timeout=20) as server:
            server.starttls()
            server.login(sender_email, app_password)
            server.send_message(msg)

        return True

    except Exception as e:
        print(f"EMAIL ERROR: {e}")
        return False